name: animatediff
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=0.13.1
  - pytorch-cuda=11.7
  - pip
  - pip:
    - diffusers==0.21.4
    - transformers==4.25.1
    - xformers==0.0.20
    - imageio==2.27.0
    - decord==0.6.0
    - cv2box==0.5.3
    - onnxruntime-gpu==1.15.1
    - gdown
    - einops
    - omegaconf
    - safetensors
    - gradio
    - wandb
